(() => {
  if (window.__MONTIS_IT_ACTIVE__) return;
  window.__MONTIS_IT_ACTIVE__ = true;

  const EXACT = {
    "7-DAY MICROCYCLE": "MICROCICLO A 7 GIORNI",
    "ANAEROBIC REPEATABILITY (WDRM)": "RIPETIBILIT\u00c0 ANAEROBICA (WDRM)",
    "DURABILITY (ISDM)": "DURABILIT\u00c0 (ISDM)",
    "NEURAL DENSITY": "DENSIT\u00c0 NEURALE",
    "MODEL DIAGNOSTICS": "DIAGNOSTICA DEL MODELLO",
    "TEMPORAL PATTERN (W\u2032 BAL)": "ANDAMENTO TEMPORALE (W\u2032 BAL)",
    "EXTERNAL LOAD CONTEXT": "CONTESTO DEL CARICO ESTERNO",
    "NUTRITION AVAILABILITY": "DISPONIBILIT\u00c0 NUTRIZIONALE",
    "DECISION STACK": "CATENA DECISIONALE",
    "READINESS & OPERATIONS": "PRONTITUDINE E OPERAZIONI",
    "LOAD SIGNALS": "SEGNALI DI CARICO",
    "PHASE GOVERNANCE": "GOVERN DELLE FASI",
    "TRAINING LOAD": "CARICO ALLENANTE",
    "PHYSIOLOGY RESPONSE": "RISPOSTA FISIOLOGICA",
    "PERFORMANCE INTELLIGENCE": "INTELLIGENZA DELLE PERFORMANCE",
    "ADAPTATION": "ADATTAMENTO",
    "ADAPTIVE DECISIONS": "DECISIONI ADATTATIVE",
    "WEEKLY TRAINING EXECUTION ANALYSIS": "ANALISI DELL'ESECUZIONE SETTIMANALE",
    "DISTANCE": "DISTANZA",
    "HOURS": "ORE",
    "WEEKLY HOURS": "ORE SETTIMANALI",
    "TOTAL TSS": "TSS TOTALE",
    "DISTANCE (KM)": "DISTANZA (KM)",
    "LOAD DIAGNOSTICS": "DIAGNOSTICA DEL CARICO",
    "METRIC": "METRICA",
    "VALUE": "VALORE",
    "STATUS": "STATO",
    "MEANING": "SIGNIFICATO",
    "EWMA acute-to-chronic workload ratio": "Rapporto carico acuto/cronico (EWMA)",
    "STRESS TOLERANCE": "TOLLERANZA ALLO STRESS",
    "Weekly load relative to CTL-based capacity": "Carico settimanale rispetto alla capacit\u00e0 basata su CTL",
    "MONOTONY": "MONOTONIA",
    "Mean daily load divided by daily load variation": "Carico medio giornaliero diviso per la variabilit\u00e0 giornaliera",
    "Weekly load multiplied by monotony": "Carico settimanale moltiplicato per la monotonia",
    "FATIGUE TREND": "TREND DI FATICABILIT\u00c0",
    "Recent 7-day load versus prior 21-day baseline": "Carico ultimi 7 giorni rispetto ai 21 giorni precedenti",
    "SLEEP SCORE": "PUNTEGGIO SONNO",
    "RESTING HR": "FC A RIPOSO",
    "HRV RATIO": "RAPPORTO HRV",
    "HRV LATEST": "HRV ATTUALE",
    "HRV MEAN": "HRV MEDIA",
    "HRV TREND": "TREND HRV",
    "OPERATIONAL STATE": "STATO OPERATIVO",
    "LOAD ACCEPTING": "ACCETTAZIONE DEL CARICO",
    "LOAD RECOVERY STATE": "STATO DI RECUPERO DAL CARICO",
    "UNKNOWN": "SCONOSCIUTO",
    "PI INTELLIGENCE SUMMARY": "SINTESI INTELLIGENZA PI",
    "MAX W\u2032 DEPLETION": "ESAURIMENTO W\u2032 MASSIMO",
    "MEAN W\u2032 DEPLETION": "ESAURIMENTO W\u2032 MEDIO",
    "NORMAL": "NORMALE",
    "7D AVERAGE": "MEDIA 7 GIORNI",
    "Work > FTP": "Lavoro > FTP",
    "High Depletion Sessions": "Sessioni ad alto esaurimento",
    "DURABILITY STATE": "STATO DI DURABILIT\u00c0",
    "COACHING IMPLICATION": "IMPLICAZIONI PER IL COACHING",
    "MEAN DECOUPLING": "DECOUPLING MEDIO",
    "ISDM MAGNITUDE": "ENTIT\u00c0 ISDM",
    "MAX DECOUPLING": "DECOUPLING MASSIMO",
    "PEAK DRIFT": "DRIFT MASSIMO",
    "HIGH DRIFT SESSIONS": "SESSIONI CON DRIFT ALTO",
    "LONG SESSIONS": "SESSIONI LUNGHE",
    "HIGH INTENSITY": "ALTA INTENSIT\u00c0",
    "DAYS": "GIORNI",
    "MEAN IF": "IF MEDIO",
    "INTENSITY": "INTENSIT\u00c0",
    "MEAN EF": "EF MEDIO",
    "VARIABILITY": "VARIABILIT\u00c0",
    "VI INDEX": "INDICE VI",
    "ANAEROBIC SIGNATURE": "FIRMA ANAEROBICA",
    "HEAT LOAD": "CARICO TERMICO",
    "MODERATE": "MODERATO",
    "CARDIO DRIFT": "DRIFT CARDIACO",
    "HEAT-INFLUENCED": "INFLUENZATO DAL CALORE",
    "NUTRITION DATA UNAVAILABLE": "DATI NUTRIZIONALI NON DISPONIBILI",
    "LACTATE CALIBRATION (LT1)": "CALIBRAZIONE LATTATO (LT1)",
    "Lactate status": "Stato lattato",
    "Not Available": "Non disponibile",
    "Samples": "Campioni",
    "Mean lactate": "Lattato medio",
    "Latest lactate": "Ultimo lattato",
    "Personalized Z2": "Z2 personalizzato",
    "Z2 as FTP %": "Z2 come % FTP",
    "Method": "Metodo",
    "DIRECTIVE": "DIRETTIVA",
    "Maintain training structure": "Mantieni la struttura di allenamento",
    "STATE": "STATO",
    "Unknown": "Sconosciuto",
    "RESOLUTION": "RISOLUZIONE",
    "RISK": "RISCHIO",
    "LOAD RECOVERY": "RECUPERO DAL CARICO",
    "LOAD TREND": "TREND DEL CARICO",
    "FORECAST": "PREVISIONE",
    "OPERATIONAL": "OPERATIVO",
    "SIGNAL": "SEGNALE",
    "No readiness signal available": "Nessun segnale di prontitudine disponibile",
    "REQUIRED PHASE": "FASE RICHIESTA",
    "ALIGNMENT": "ALLINEAMENTO",
    "Athlete": "Atleta",
    "ATHLETE": "ATLETA",
    "SUNRISE": "ALBA",
    "MON": "LUN",
    "TUE": "MAR",
    "WED": "MER",
    "THU": "GIO",
    "FRI": "VEN",
    "SAT": "SAB",
    "SUN": "DOM",
    "MON TUE WED THU FRI SAT SUN": "LUN MAR MER GIO VEN SAB DOM",
    "NO ACTIVE ISO-WEEK PLAN DETECTED FOR THIS BLOCK.": "NESSUN PIANO ISO-SETTIMANA ATTIVO PER QUESTO BLOCCO.",
    "REPORT STATUS: PARTIAL / INSUFFICIENT DATA": "STATO REPORT: PARZIALE / DATI INSUFFICIENTI",
    "PRIVACY POLICY": "PRIVACY",
    "TERMS OF SERVICE": "TERMINI DI SERVIZIO",
    "PROFILE": "PROFILO",
    "WELLNESS": "BENESSERE",
    "Performance Progression": "Progressione della Performance",
    "FTP / EFTP": "FTP / eFTP",
    "W/KG": "W/KG",
    "MAX / LTHR": "MAX / FC SOGLIA",
    "(deep dive)": "(approfondimento)",
    "Weight": "Peso",
    "Max HR": "FC Max",
    "Base FTP": "FTP base",
    "Lactate Pwr": "Potenza al lattato",
    "No active subscription or supporter record.": "Nessun abbonamento attivo n\u00e9 record di sostenitore.",
    "Load Order": "Ordine di priorit\u00e0",
    "POWER > HR > PACE": "POTENZA > FC > RITMO",
    "Power Zones (W)": "Zone di potenza (W)",
    "HR Zones (bpm)": "Zone FC (bpm)",
    "GAP Model": "Modello GAP",
    "POWER > PACE > HR": "POTENZA > RITMO > FC",
    "Athlete Intelligence Profile \u2022 Montis Intelligence v5.1": "Profilo Intelligenza Atleta \u2022 Montis Intelligence v5.1",
    "HRV (ms) Trend": "Trend HRV (ms)",
    "AUTONOMIC STATUS": "STATO AUTONOMICO",
    "Recovery Markers": "Marcatori di recupero",
    "Metric Highlights": "Evidenze delle metriche",
    "AI DEEP DIVE ANALYSIS": "ANALISI APPROFONDITA IA",
    "Latest Trend": "Trend recente",
    "42-Day Autonomic & Wellness Analysis": "Analisi autonomica e benessere \u2014 42 giorni",
    "\u2022 Last Updated:": "\u2022 Ultimo aggiornamento:",
    "Resting Heart Rate": "Frequenza cardiaca a riposo",
    "Body Battery": "Batteria corporea",
    "PEAK DAILY ENERGY": "ENERGIA GIORNALIERA DI PICCO",
    "ACTIVE RECOVERY": "RECUPERO ATTIVO",
    "Banister Capacity-Adjusted Load Ratio": "Rapporto carico aggiustato per capacit\u00e0 (Banister)",
    "Monotony": "Monotonia",
    "HRV relative to 42-day mean": "HRV rispetto alla media a 42 giorni",
    "hrv stability index": "indice di stabilit\u00e0 HRV",
    "sleep quality": "qualit\u00e0 del sonno",
    "42-Day Interpretation \u2022 Metric:": "Interpretazione 42 giorni \u2022 Metrica:",
    "HRV (MS) 42-DAY DEEP DIVE": "HRV (MS) ANALISI PROFONDA 42 GIORNI",
    "Analysis History": "Cronologia delle analisi",
    "Review previous coaching reports and tool outputs.": "Rivedi i report di coaching precedenti e gli output degli strumenti.",
    "Coaching Directive": "Direttiva di coaching",
    "Montis Intelligence Stack \u2022 Unified Reporting Framework v": "Montis Intelligence Stack \u2022 Framework di Reporting Unificato v",
    "Montis Coaching Intelligence Design": "Design dell'intelligenza di coaching Montis",
    "Coaching Intelligence Pipeline": "Pipeline d'intelligenza del coaching",
    "The Five Intelligence Layers": "I cinque livelli d'intelligenza",
    "1 \u2014 TRAINING LOAD": "1 \u2014 CARICO ALLENANTE",
    "2 \u2014 PHYSIOLOGY RESPONSE": "2 \u2014 RISPOSTA FISIOLOGICA",
    "3 \u2014 PERFORMANCE INTELLIGENCE": "3 \u2014 INTELLIGENZA DELLE PERFORMANCE",
    "5 \u2014 ADAPTIVE DECISION ENGINE": "5 \u2014 MOTORE DI DECISIONI ADATTATIVE",
    "ADE BASE DECISION \u2014 CAN": "DECISIONE BASE ADE \u2014 POSSO",
    "PHASE AND EVENT GOVERNANCE \u2014 SHOULD": "GOVERN DI FASE ED EVENTO \u2014 DEVO",
    "Final Resolution": "Risoluzione finale",
    "Historical Report Safety": "Sicurezza dei report storici",
    "How to Use the Help Manual": "Come usare il manuale della Guida",
    "Comprehensive guide to maximising the engine": "Guida completa per sfruttare al meglio il motore",
    "What does this data mean?": "Cosa significano questi dati?",
    "How is the athlete responding?": "Come sta rispondendo l'atleta?",
    "Is adaptation occurring?": "L'adattamento \u00e8 in corso?",
    "Is the current load being absorbed?": "Il carico attuale viene assorbito?",
    "It is the relationship between them.": "\u00c8 la relazione tra di essi.",
    "Intervals.icu provides the data.": "Intervals.icu fornisce i dati.",
    "Montis makes the data meaningful.": "Montis rende i dati significativi.",
    "How much stress was applied?": "Quanto stress \u00e8 stato applicato?",
    "How is the body responding?": "Come sta rispondendo il corpo?",
    "Its current model contracts include:": "I vincoli di modello attuali includono:",
    "\u2014 anaerobic repeatability and W\u2032 depletion behaviour.": "\u2014 ripetibilit\u00e0 anaerobica e comportamento di esaurimento del W\u2032.",
    "\u2014 durability and cardiovascular drift.": "\u2014 durabilit\u00e0 e drift cardiovascolare.",
    "\u2014 high-intensity density and execution characteristics.": "\u2014 densit\u00e0 ad alta intensit\u00e0 e caratteristiche di esecuzione.",
    "For ADE, the operational state is simplified to:": "Per l'ADE, lo stato operativo si semplifica in:",
    "Can the athlete currently tolerate further training stress?": "L'atleta pu\u00f2 tollerare ulteriore stress di allenamento?",
    "energy-system status;": "stato dei sistemi energetici;",
    "adaptation state;": "stato di adattamento;",
    "power-model context;": "contesto del modello di potenza;",
    "adaptation bias;": "bias di adattamento;",
    "The dashboard": "La dashboard",
    "Adaptation Pulse": "Impulso di adattamento",
    "ADE v2.21 is the operational decision layer.": "ADE v2.21 \u00e8 il livello decisionale operativo.",
    "What can the athlete tolerate now?": "Cosa pu\u00f2 tollerare l'atleta adesso?",
    "forecast fatigue and load trend;": "previsione fatica e trend del carico;",
    "HRV guardrail;": "barriera HRV;",
    "ESPE adaptation state;": "stato adattativo ESPE;",
    "target-event and taper context;": "contesto evento-obiettivo e taper;",
    "pre-phase-governance": "pre-govern di fase",
    "base score and directive.": "punteggio base e direttiva.",
    "This represents immediate operational capacity.": "Rappresenta la capacit\u00e0 operativa immediata.",
    "Phase and event governance = SHOULD": "Govern di fase/evento = DOVEREI",
    "Strategic governance considers:": "Il govern strategico considera:",
    "current and projected phase;": "fase attuale e proiettata;",
    "recent fatigue/recovery requirements;": "requisiti recenti di fatica/recupero;",
    "planned load direction;": "direzione di carico pianificata;",
    "target-event context;": "contesto dell'evento-obiettivo;",
    "projected event form;": "forma proiettata per l'evento;",
    "The first statement describes operational capacity.": "La prima affermazione descrive la capacit\u00e0 operativa.",
    "The final governed action can be classified as:": "L'azione finale governata pu\u00f2 essere classificata come:",
    "ADE and strategic governance agree": "ADE e govern strategico concordano",
    "Phase or event governance overrides the ADE base directive": "Il govern di fase o evento prevale sulla direttiva base dell'ADE",
    "It does not recompute Performance Intelligence, ESPE or ADE.": "Non ricalcola Performance Intelligence, ESPE o ADE.",
    "The distinction is:": "La distinzione \u00e8:",
    "The LLM is a read-only interpretation layer.": "L'LLM \u00e8 un livello di interpretazione in sola lettura.",
    "explain the governed result;": "spiegare il risultato governato;",
    "present the training state clearly;": "presentare chiaramente lo stato di allenamento;",
    "summarise the reasons;": "riassumere le motivazioni;",
    "override the ADE result;": "sovrascrivere il risultato dell'ADE;",
    "create an alternative coaching directive;": "creare una direttiva di coaching alternativa;",
    "modify the training calendar without explicit execution.": "modificare il calendario senza esecuzione esplicita.",
    "For stale historical weekly reports, Montis can:": "Per i report settimanali storici non aggiornati, Montis pu\u00f2:",
    "suppress live event-readiness guidance;": "sopprimere le indicazioni live di prontitudine alla gara;",
    "remove current taper instructions;": "rimuovere le istruzioni di taper correnti;",
    "reframe the result as historical block analysis.": "riformulare il risultato come analisi storica del blocco.",
    "how the complete Montis architecture fits together": "come si incastra l'architettura completa di Montis",
    "For detailed methodology, use the five Science sections:": "Per la metodologia dettagliata, usa le cinque sezioni Scienza:",
    "\u2014 how the stack is presented across time horizons.": "\u2014 come lo stack si presenta attraverso gli orizzonti temporali.",
    "\u2014 how wellness measurements are displayed and interpreted.": "\u2014 come le misurazioni del benessere vengono mostrate e interpretate.",
    "Race Readiness": "Prontitudine alla gara",
    "\u2014 event, form, taper and readiness governance.": "\u2014 govern di evento, forma, taper e prontitudine.",
    "\u2014 workout creation, planning and execution workflow.": "\u2014 flusso di creazione, pianificazione ed esecuzione degli allenamenti.",
    "Training Load establishes the applied stress.": "Il Carico Allenante stabilisce lo stress applicato.",
    "Physiology Response evaluates how the body is responding.": "La Risposta Fisiologica valuta come sta reagendo il corpo.",
    "ADE determines what the athlete can tolerate.": "L'ADE determina ci\u00f2 che l'atleta pu\u00f2 tollerare.",
    "URF governs how the validated result is reported.": "L'URF governa come viene riportato il risultato validato.",
    "Dashboard Horizons & Montis Intelligence Stack": "Orizzonti della Dashboard & Stack d'Intelligenza Montis",
    "Micro \u2014 Weekly Horizon": "Micro \u2014 Orizzonte settimanale",
    "Meso \u2014 Training Block Horizon": "Meso \u2014 Orizzonte del blocco di allenamento",
    "Macro \u2014 Summary Horizon": "Macro \u2014 Orizzonte riassuntivo",
    "Readiness \u2014 Target Events": "Prontitudine \u2014 Eventi obiettivo",
    "Calendar (Forecast)": "Calendario (previsione)",
    "AI Coaching Engine": "Motore di Coaching IA",
    "Session Intensity Lab (SIL)": "Laboratorio Intensit\u00e0 Sessione (SIL)",
    "Performance Progression & Pathway Analysis": "Progressione della Performance & Analisi del Percorso",
    "Lactate Integration & Personalised Zone 2": "Integrazione Lattato & Zona 2 Personalizzata",
    "Science \u2192 Training Load": "Scienza \u2192 Carico Allenante",
    "Science \u2192 Physiology Response": "Scienza \u2192 Risposta Fisiologica",
    "Science \u2192 Performance Intelligence (PI)": "Scienza \u2192 Intelligenza delle Performance (PI)",
    "Science \u2192 Adaptive Decision Engine (ADE)": "Scienza \u2192 Motore di Decisioni Adattative (ADE)",
    "42-Day Autonomic & Wellness Analysis \u2022": "Analisi autonomica e benessere \u2014 42 giorni \u2022",
    "This document describes the": "Questo documento descrive il",
    "current production design": "design di produzione attuale",
    "and how the Montis Intelligence Stack fits together.": "e come si incastra il Montis Intelligence Stack.",
    "What does the future plan imply?": "Cosa implica il piano futuro?",
    "The value of Montis is therefore not simply the number of metrics displayed.": "Il valore di Montis quindi non \u00e8 semplicemente il numero di metriche mostrate.",
    "Training Load establishes the objective stress applied to the athlete.": "Il Carico Allenante stabilisce lo stress oggettivo applicato all'atleta.",
    "Physiology Response evaluates how the athlete is responding to the applied stress.": "La Risposta Fisiologica valuta come l'atleta reagisce allo stress applicato.",
    "Performance Intelligence models the athlete's current capabilities.": "L'Intelligenza delle Performance modella le capacit\u00e0 attuali dell'atleta.",
    "Adaptive Decisions determine the appropriate training action.": "Le Decisioni Adattative determinano l'azione di allenamento appropriata.",
    "Sleep": "Sonno",
    "Ratio": "Rapporto",
    "METRICS": "METRICHE",
    "StressTolerance": "Tolleranza allo stress",
    "Science & Methodology": "Scienza e metodologia",
    "Why Montis Shows More Than Raw Metrics": "Perch\u00e9 Montis mostra pi\u00f9 delle metriche grezze",
    "Intervals.icu provides the underlying training data, metrics and calendar context.": "Intervals.icu fornisce i dati di allenamento sottostanti, le metriche e il contesto del calendario.",
    "Montis adds a governed interpretation layer on top of that data.": "Montis aggiunge un livello di interpretazione governata sopra tali dati.",
    "Detailed methodology:": "Metodologia dettagliata:",
    "Is the athlete absorbing and expressing the applied load effectively?": "L'atleta sta assorbendo ed esprimendo efficacemente il carico applicato?",
    "Performance Intelligence also contributes to the consolidated Training State used by ": "L'Intelligenza delle Performance contribuisce anche allo Stato di Allenamento consolidato usato da ",
    "Performance Intelligence also contributes to the consolidated Training State used by ADE.": "L'Intelligenza delle Performance contribuisce anche allo Stato di Allenamento consolidato usato dall'ADE.",
    "These states answer:": "Questi stati rispondono:",
    "is a presentation of ESPE output, not a separate adaptation model.": "\u00e8 una presentazione dell'output ESPE, non un modello di adattamento separato.",
    "Science \u2192 Energy System Progression (ESPE) & Phase Development": "Scienza \u2192 Progressione dei Sistemi Energetici (ESPE) & Sviluppo delle Fasi",
    "operational state;": "stato operativo;",
    "supplementary nutrition context where confidence is sufficient.": "contesto nutrizionale supplementare dove la confidenza \u00e8 sufficiente.",
    "Montis deliberately preserves two different decisions.": "Montis preserva deliberatamente due decisioni diverse.",
    "Can: continue productive loading\nShould: recover and consolidate adaptation": "Posso: continuare un carico produttivo\nDovrei: recuperare e consolidare l'adattamento",
    "URF v5.1 governs how validated Montis outputs are organised and rendered into reports": "URF v5.1 governa come gli output validati di Montis sono organizzati e resi nei report",
    "URF v5.1 governs how validated Montis outputs are organised and rendered into reports.": "URF v5.1 governa come gli output validati di Montis sono organizzati e resi nei report.",
    "recalculate canonical metrics;": "ricalcolare le metriche canoniche;",
    "invent missing values;": "inventare valori mancanti;",
    "Workouts & AI Builder": "Allenamenti & Costruttore IA",
    "Phase and event governance determine what the athlete should do.": "Il govern di fase ed evento determina ci\u00f2 che l'atleta dovrebbe fare.",
    "Science \u2014 Training Load": "Scienza \u2014 Carico Allenante",
    "Science \u2014 Physiology Response": "Scienza \u2014 Risposta Fisiologica",
    "Science \u2014 Performance Intelligence (PI)": "Scienza \u2014 Intelligenza delle Performance (PI)",
    "Science \u2014  Energy System Progression (ESPE) & Phase Development": "Scienza \u2014 Progressione dei Sistemi Energetici (ESPE) & Sviluppo delle Fasi",
    "Science \u2014 Adaptive Decision Engine (ADE)": "Scienza \u2014 Motore di Decisioni Adattative (ADE)",
    "Overview \u2014 Today Horizon": "Panoramica \u2014 Orizzonte di oggi",
    "Micro \u2014 Weekly Horizon": "Micro \u2014 Orizzonte settimanale",
    "Meso \u2014 Training Block Horizon": "Meso \u2014 Orizzonte del blocco di allenamento",
    "Macro \u2014 Summary Horizon": "Macro \u2014 Orizzonte riassuntivo",
    "Readiness \u2014 Target Events": "Prontitudine \u2014 Eventi obiettivo",
    "Sandbox (Playground)": "Sandbox (area prove)",
    "Wellness & Physiology": "Benessere e fisiologia",
    "Montis Skills": "Competenze Montis",
    "Weekly Activity Check": "Controllo attivit\u00e0 settimanale",
    "Exercise days": "Giorni di esercizio",
    "Active Week": "Settimana attiva",
    "WEEK": "SETTIMANA",
    "Weekly TSS Target": "Target TSS settimanale",
    "Weekly Duration": "Durata settimanale",
    "TIER 5 \u2022 DECISION ENGINE": "LIVELLO 5 \u2022 MOTORE DECISIONALE",
    "ADAPTIVE DECISION ENGINE": "MOTORE DI DECISIONI ADATTATIVE",
    "ADE Base Score": "Punteggio base ADE",
    "Mesocycle Phase Analysis": "Analisi delle fasi del mesociclo",
    "PHASE": "FASE",
    "LOAD (CTL/ATL/TSB)": "CARICO (CTL/ATL/TSB)",
    "Peak (Stable/Fresh)": "Picco (Stabile/Fresco)",
    "Transition (Phase)": "Transizione (Fase)",
    "Cycle": "Ciclo",
    "Anaerobic Integrity": "Integrit\u00e0 anaerobica",
    "Mean W'Bal Depletion": "Esaurimento medio W'Bal",
    "Mean W\u2032Bal Depletion": "Esaurimento medio W\u2032Bal",
    "Weekly Peaks": "Picchi settimanali",
    "Anaerobic Contrib (%)": "Contributo anaerobico (%)",
    "Macrocycle Macro-Totals": "Totali complessivi del macrociclo",
    "FATIGUE STATE": "STATO DI FATICABILIT\u00c0",
    "Annual Training Timeline (Weekly Resolution)": "Cronologia annuale dell'allenamento (risoluzione settimanale)",
    "Mean IF (%)": "IF medio (%)",
    "Aerobic Index": "Indice aerobico",
    "Physio-Efficiency": "Efficienza fisiologica",
    "Timeline Forecast": "Previsione cronologica",
    "Active Projection": "Proiezione attiva",
    "Drag and drop events to move to a different date": "Trascina gli eventi per spostarli a una data diversa",
    "Load": "Carico",
    "Phase Detection": "Rilevamento della fase",
    "planned activities": "activit\u00e0 pianificate",
    "Select Target Event": "Seleziona evento obiettivo",
    "Go to Forecast": "Vai alla previsione",
    "Banister Load & ACWR Workload Simulator": "Simulatore carico Banister & workload ACWR",
    "ADAPTIVE FORECAST": "PREVISIONE ADATTATIVA",
    "Planned Workout TSS": "TSS dell'allenamento pianificato",
    "FORECAST CTL": "PREVISIONE CTL",
    "FORECAST ATL": "PREVISIONE ATL",
    "FORECAST TSB": "PREVISIONE TSB",
    "Under-Training State": "Stato di sotto-allenamento",
    "Autonomic Physiology Readiness Predictor": "Predittore di prontitudine fisiologica autonomica",
    "SYSTEMIC REST STATUS": "STATO DI RIPOSO SISTEMICO",
    "Restful Sleep Score": "Punteggio sonno ristoratore",
    "Fatigue Level": "Livello di fatica",
    "Insufficient data detected for this period. Try a different date range or a demo report.": "Dati insufficienti per questo periodo. Prova un intervallo di date diverso o un report demo.",
    "2. PLAN GOVERNANCE": "2. GOVERN DEL PIANO",
    "RESOLUTION STATE": "STATO DI RISOLUZIONE",
    "TIER 1 \u2022 LOAD STATE": "LIVELLO 1 \u2022 STATO DEL CARICO",
    "Fitness": "Condizione",
    "Fatigue": "Fatica",
    "LOAD PATTERN": "SCHEMA DI CARICO",
    "LOAD STATE": "STATO DEL CARICO",
    "Wellness Vitals Grid": "Griglia dei parametri vitali del benessere",
    "Physiology Reserve": "Riserva fisiologica",
    "Rest": "Riposo",
    "5m (Vo2 Block)": "5m (blocco VO2)",
    "10m (Threshold Interval)": "10m (intervallo a soglia)",
    "BALANCED LOAD": "CARICO EQUILIBRATO",
    "TIER 2 \u2022 AUTONOMIC READINESS": "LIVELLO 2 \u2022 PRONTITUDINE AUTONOMICA",
    "HRV ratio + resting HR delta + sleep + TSB + subjective signals": "Rapporto HRV + delta FC riposo + sonno + TSB + segnali soggettivi",
    "ESTIMATED MEANING": "SIGNIFICATO STIMATO",
    "TIER 3 \u2022 COGNITIVE FITNESS": "LIVELLO 3 \u2022 CONDIZIONE COGNITIVA",
    "Performance Intelligence (PI)": "Intelligenza delle Performance (PI)",
    "INTELLIGENCE SIGNAL": "SEGNALE D'INTELLIGENZA",
    "Durability": "Durabilit\u00e0",
    "Adaptation Progression (ESPE)": "Progressione dell'adattamento (ESPE)",
    "ADAPTATION COMMENTARY": "COMMENTO SULL'ADATTAMENTO",
    "Energy system profile is tracking within established baseline progression windows.": "Il profilo dei sistemi energetici procede entro le finestre di progressione baseline stabilite.",
    "ADAPTATION PROFILE": "PROFILO D'ADATTAMENTO",
    "MIXED ADAPTATION": "ADATTAMENTO MISTO",
    "Average daily intake across the three most recent completed nutrition days": "Assunzione media giornaliera degli ultimi tre giorni nutrizionali completati",
    "Scientific Adaptation": "Adattamento scientifico",
    "Efficiency Factor": "Fattore di efficienza",
    "Directional gradients of your training cycles": "Gradienti direzionali dei tuoi cicli di allenamento",
    "Performance Intelligence Priority": "Priorit\u00e0 dell'Intelligenza delle Performance",
    "Acute: Readiness": "Acuto: prontitudine",
    "Chronic: Adaptation": "Cronico: adattamento",
    "Durability Breakdown": "Scomposizione della durabilit\u00e0",
    "Acute (7d) Readiness": "Acuto (7g): prontitudine",
    "Chronic (90d) Adaptation": "Cronico (90g): adattamento",
    "Measures aerobic stability. Low values across both indicate a high durability floor.": "Misura la stabilit\u00e0 aerobica. Valori bassi su entrambi indicano un pavimento di durabilit\u00e0 elevato.",
    "Acute Density (Days)": "Densit\u00e0 acuta (giorni)",
    "Sessions": "Sessioni",
    "Clustering of hard efforts. High acute density increases recovery debt beyond simple TSS.": "Accumulo di sforzi intensi. Un'elevata densit\u00e0 acuta aumenta il debito di recupero oltre il semplice TSS.",
    "Anaerobic Stress": "Stress anaerobico",
    "Peak W' Depletion": "Picco di esaurimento W'",
    "Peak W\u2032 Depletion": "Picco di esaurimento W\u2032",
    "Mean Profile Depth": "Profondit\u00e0 media del profilo",
    "Supra-threshold exposure. Tracks how deep you go vs how much you lean on this system.": "Esposizione sopra-soglia. Traccia quanto vai in profondit\u00e0 rispetto a quanto dipendi da questo sistema.",
    "anaerobic": "anaerobico",
    "baseline": "baseline",
    "threshold": "soglia",
    "aerobic durability": "durabilit\u00e0 aerobica",
    "Mean W' Prime": "W' medio",
    "Mean W\u2032 Prime": "W\u2032 medio",
    "Mean HRV": "HRV media",
    "Avg Sleep Score": "Punteggio sonno medio",
    "Fat Oxidation Index": "Indice di ossidazione dei grassi",
    "FatOx index %": "Indice FatOx %",
    "Training Diet (Yearly)": "Alimentazione allenante (annuale)",
    "Productive Fatigue": "Fatica produttiva",
    "structured": "settimane strutturate",
    "training weeks based on physiological Form (TSB).": "di allenamento basate sulla forma fisiologica (TSB).",
    "High Impact Sessions & Anomalies": "Sessioni ad alto impatto e anomalie",
    "DETECTED": "RILEVATE",
    "vs Mean": "vs media",
    "Lab Analysis": "Analisi da laboratorio",
    "Microcycle training stress distribution compared against historic chronic load capacity.": "Distribuzione dello stress d'allenamento del microciclo rispetto alla capacit\u00e0 di carico cronica storica.",
    "Insufficient stress. Long term fitness losses.": "Stress insufficiente. Perdite di condizione a lungo termine.",
    "bpm (Infection / Stress)": "bpm (infezione / stress)",
    "Subjective systemic and central nervous system fatigue": "Fatica soggettiva sistemica e del sistema nervoso centrale",
    "Psychological Stress": "Stress psicologico",
    "Life load, sleep disruptions, and sympathetic hyper-arousal": "Carico di vita, disturbi del sonno e iperattivazione simpatica",
    "AUTONOMIC SCORE": "PUNTEGGIO AUTONOMICO",
    "Mild Sympathetic Fatigue": "Fatica simpatica lieve",
    "W' (Anaerobic Repeatability Capacity) Depletion Sandbox": "Sandbox esaurimento W' (capacit\u00e0 di ripetibilit\u00e0 anaerobica)",
    "SKIBA CP MODEL": "MODELLO CP SKIBA",
    "SELECT INTENSITY LEVEL BLOCK": "SELEZIONA BLOCCO DI LIVELLO D'INTENSIT\u00c0",
    "Aerobic Build": "Costruzione aerobica",
    "FTP Power": "Potenza FTP",
    "Anaerobic Load": "Carico anaerobico",
    "Aerobic Equilibrium (No depletion)": "Equilibrio aerobico (nessun esaurimento)",
    "Multi-duration power profile and repeatability progression state.": "Profilo di potenza multi-durata e stato di progressione della ripetibilit\u00e0.",
    "TREFF & ESPE MODEL": "MODELLO TREFF & ESPE",
    "CHOOSE TRAIN INTENSITY MODEL": "SCEGLI IL MODELLO D'INTENSIT\u00c0 DI ALLENAMENTO",
    "High aerobic volume paired with clean HIIT intensity splits.": "Ampio volume aerobico abbinato a frazioni HIIT pulite.",
    "Moderate threshold/tempo volume build suitable for marathon blocks.": "Costruzione moderata di volume a soglia/tempo adatta ai blocchi maratona.",
    "Threshold-Heavy (60/32/8)": "Soglia-dominante (60/32/8)",
    "Extensive sweetspot/FTP duration build. Risk of aerobic fatigue plateau.": "Costruzione estesa su durata sweetspot/FTP. Rischio di plateau di fatica aerobica.",
    "Treff Polarization Index": "Indice di polarizzazione Treff",
    "Estimated one-workout impact on load, fatigue and readiness signals.": "Impatto stimato di un singolo allenamento su carico, fatica e segnali di prontitudine.",
    "WHAT-IF LOAD IMPACT": "IMPATTO CARICO WHAT-IF",
    "WHAT WOULD THIS SESSION CHANGE?": "COSA CAMBEREBBE CON QUESTA SESSIONE?",
    "1. SANDBOX SIGNAL CHANGE": "1. VARIAZIONE SEGNALE SANDBOX",
    "Current": "Attuale",
    "2. ESTIMATED LOAD STATE IMPACT": "2. IMPATTO STIMATO SULLO STATO DI CARICO",
    "Current ADE": "ADE attuale",
    "CLEARED DIRECTIVE SUSTAINED": "DIRETTIVA CONFERMATA SENZA CAMBIAMENTI",
    "Directive unchanged. No workout load applied.": "Direttiva invariata. Nessun carico applicato.",
    "The report is historical and is not valid as current tactical guidance": "Il report \u00e8 storico e non \u00e8 valido come indicazione tattica attuale",
    "Current weekly guidance is tactical only when the report is current.": "Le indicazioni settimanali sono tattiche solo quando il report \u00e8 aggiornato."
  };

  const SUBSTR = [
    ["REPORT STATUS", "STATO REPORT"],
    ["PARTIAL / INSUFFICIENT DATA", "PARZIALE / DATI INSUFFICIENTI"],
    ["INSUFFICIENT DATA", "DATI INSUFFICIENTI"],
    ["\u2022 Last Updated:", "\u2022 Ultimo aggiornamento:"],
    ["Last Updated:", "Ultimo aggiornamento:"],
    ["UPDATED:", "AGGIORNATO:"],
    ["\u2022 Updated:", "\u2022 Aggiornato:"],
    ["Updated:", "Aggiornato:"],
    ["TIMEZONE:", "FUSO ORARIO:"],
    ["Timezone:", "Fuso orario:"],
    ["(deep dive)", "(approfondimento)"],
    ["(last 7 days)", "(ultimi 7 giorni)"],
    ["(last 42 days)", "(ultimi 42 giorni)"],
    ["(last 84d v previous 84d)", "(ultimi 84g vs 84g prec.)"],
    ["last 84d v previous 84d", "ultimi 84g vs 84g prec."],
    ["Latest RHR:", "Ultima FC a riposo:"],
    ["MEAN:", "MEDIA:"],
    ["Rating:", "Valutazione:"],
    ["Score:", "Punteggio:"],
    ["Status:", "Stato:"],
    ["Scale:", "Scala:"],
    ["Delta:", "Delta:"],
    ["Baseline", "Base"],
    ["(Baseline", "(Base"],
    ["TSS Over Target", "TSS oltre il target"],
    ["\u2014 UNKNOWN", "\u2014 SCONOSCIUTO"],
    ["& Future Cycles", "& cicli futuri"],
    ["Exercise days:", "Giorni di esercizio:"],
    ["bpm (Infection / Stress)", "bpm (infezione / stress)"],
    ["Target=", "Obiettivo="]
  ];

  const SKIP = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "TEXTAREA"]);
  const SKIP_CLS = ["cpsl-panel"];

  const EXACT_UPPER = {};
  for (const [k, v] of Object.entries(EXACT)) {
    const kk = k.replace(/\s+/g, " ").trim();
    const vv = v;
    delete EXACT[k];
    EXACT[kk] = vv;
    if (!EXACT_UPPER[kk.toUpperCase()]) EXACT_UPPER[kk.toUpperCase()] = vv;
  }

  function trText(s) {
    const trimmed = s.trim();
    if (!trimmed) return null;
    const norm = trimmed.replace(/\s+/g, " ");
    let rep = EXACT[norm] || EXACT_UPPER[norm.toUpperCase()];
    if (rep) return s.replace(trimmed, rep);
    let out = s;
    let hit = false;
    for (const [a, b] of SUBSTR) {
      if (out.includes(a)) { out = out.split(a).join(b); hit = true; }
    }
    return hit ? out : null;
  }

  function walk(root) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) {
      const n = walker.currentNode;
      const p = n.parentElement;
      if (!p || SKIP.has(p.tagName)) continue;
      if (SKIP_CLS.some(c => p.closest("." + c))) continue;
      nodes.push(n);
    }
    for (const n of nodes) {
      const r = trText(n.nodeValue);
      if (r && r !== n.nodeValue) n.nodeValue = r;
    }
    const els = root.querySelectorAll ? root.querySelectorAll("[aria-label],[title],[placeholder]") : [];
    for (const el of els) {
      for (const attr of ["aria-label", "title", "placeholder"]) {
        const v = el.getAttribute(attr);
        if (!v) continue;
        const r = trText(v);
        if (r && r !== v) el.setAttribute(attr, r);
      }
    }
  }

  let scheduled = false;
  function schedule() {
    if (scheduled) return;
    scheduled = true;
    requestAnimationFrame(() => {
      scheduled = false;
      walk(document.body);
    });
  }

  walk(document.body);
  window.__montisItValues = new Set(Object.values(EXACT).concat(SUBSTR.map(s => s[1])));
  const obs = new MutationObserver(muts => {
    for (const m of muts) {
      for (const n of m.addedNodes) {
        if (n.nodeType === 3) { const r = trText(n.nodeValue); if (r && r !== n.nodeValue) n.nodeValue = r; }
        else if (n.nodeType === 1 && !SKIP.has(n.tagName)) schedule();
      }
      if (m.type === "characterData") {
        const r = trText(m.target.nodeValue);
        if (r && r !== m.target.nodeValue) m.target.nodeValue = r;
      }
    }
  });
  obs.observe(document.body, { childList: true, subtree: true, characterData: true });

  window.__montisItTranslate = () => walk(document.body);
})();
